create table truck
(
    id              int generated by default as identity primary key,
    license_plate   varchar(10) not null unique check (btrim(license_plate) <> ''),
    max_capacity_kg int         not null check (max_capacity_kg > 0)
);

create table route
(
    id          int generated by default as identity primary key,
    name        varchar(100) not null check (btrim(name) <> ''),
    distance_km int          not null check (distance_km > 0),
    origin      varchar(100) not null check (btrim(origin) <> ''),
    destination varchar(100) not null check (btrim(destination) <> ''),
    check (origin <> destination)
);

create table truck_load
(
    id        int generated by default as identity primary key,
    truck_id  int          not null references truck (id),
    weight_kg int          not null check (weight_kg > 0),
    detail    varchar(300) not null check (btrim(detail) <> '')
);

create table truck_route
(
    truck_id int not null references truck (id) on delete cascade,
    route_id int not null references route (id) on delete cascade,
    primary key (truck_id, route_id)
);

create index idx_truck_load_truck_id
    on truck_load (truck_id);

insert into truck (license_plate, max_capacity_kg)
values
    ('abcd-12', 1000),
    ('efgh-34', 2000),
    ('ijkl-56', 3500);

insert into route (name, distance_km, origin, destination)
values
    ('ruta costera', 120, 'santiago', 'valparaíso'),
    ('ruta sur', 500, 'santiago', 'concepción'),
    ('ruta norte', 470, 'santiago', 'la serena');

insert into truck_load (truck_id, weight_kg, detail)
values
    ((select id from truck where license_plate = 'abcd-12'), 300, 'cajas de alimentos'),
    ((select id from truck where license_plate = 'abcd-12'), 400, 'muebles'),
    ((select id from truck where license_plate = 'efgh-34'), 500, 'electrodomésticos'),
    ((select id from truck where license_plate = 'efgh-34'), 700, 'materiales de construcción');

insert into truck_route (truck_id, route_id)
values
    (
        (select id from truck where license_plate = 'abcd-12'),
        (select id from route where name = 'ruta costera')
    ),
    (
        (select id from truck where license_plate = 'abcd-12'),
        (select id from route where name = 'ruta sur')
    ),
    (
        (select id from truck where license_plate = 'efgh-34'),
        (select id from route where name = 'ruta norte')
    ),
    (
        (select id from truck where license_plate = 'ijkl-56'),
        (select id from route where name = 'ruta sur')
    );