create table client
(
    id       int generated by default as identity primary key,
    name     varchar(150) not null check (btrim(name) <> ''),
    email    varchar(150) not null unique check (btrim(email) <> ''),
    phone    varchar(20)
);

create table shipment
(
    id          int generated by default as identity primary key,
    client_id   int          not null references client (id),
    truck_id    int          not null,
    load_id     int,
    weight_kg   int          not null check (weight_kg > 0),
    detail      varchar(300) not null check (btrim(detail) <> ''),
    status      varchar(20)  not null default 'REGISTERED'
        check (status in ('REGISTERED', 'REVERTED')),
    created_at  timestamp    not null default now()
);

create index idx_shipment_client_id
    on shipment (client_id);

create index idx_shipment_truck_id
    on shipment (truck_id);